### ISSUE TITLE
Temperature compensation fails

### ISSUE THREAD

**Issue by albielew** [RequestForCoffee/scd30#7]
The temperature compensation fails to write to the register and always stays the same

**Comment by ndevenish** [comment]
I thought I had this issue also, but it seems to actually be a case of slow response - nothing happened on writing the compensation, but slowly the reported temperature drifts down to (or near to) the offset. This appears to be alluded to in the function documentation: https://github.com/RequestForCoffee/scd30/blob/966b03fc32db3b0942960acc9823e827762596e1/scd30_i2c/__init__.py#L313-L314
