### ISSUE TITLE
Sample code doesn’t work

### ISSUE THREAD

**Issue by Rastisan** [RequestForCoffee/scd30#9]
Hi, 

I’m quite new to the scene and I can’t manage to make the sample code work on my raspi 4B.
I’ve followed the instructions, installed the scd30_i2c package, did the wiring and copied the sample code to Thonny IDE on my raspi that I access trough VNC. When runing the code I get the following error msgs:

"
Traceback (most recent call last):
  File "/home/pita/Documents/Malina SCD30 test.py", line 5, in <module>
    scd30 = SCD30()
  File "/home/pita/.local/lib/python3.7/site-packages/scd30_i2c/__init__.py", line 17, in __init__
    self._i2c = smbus2.SMBus(1)
  File "/home/pita/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 279, in __init__
    self.open(bus)
  File "/home/pita/.local/lib/python3.7/site-packages/smbus2/smbus2.py", line 308, in open
    self.fd = os.open(filepath, os.O_RDWR)
PermissionError: [Errno 13] Permission denied: '/dev/i2c-1'
"

I think this is because I did not do something in the "Software configuration and I²C clock stretching" part of the tutorial. This is because this part is clarifying why i2c clock stretching is required but it doesn’t give precise instructions on how to achieve the software configuration and I2C clock stretching. 

Please advise what do I need to do in this part of the tutorial.

Thank you, cheers!

**Comment by patwil** [comment]
I'm guessing that this is because you do not have the requisite permission to read `/dev/i2c-*`.
This can be fixed by adding yourself to the i2c group:
```
sudo usermod -a -G i2c $USER
```
_Note that you will need to log out and in again for this to take effect._

You can also try running the Python script using `sudo`.

**Comment by Rastisan** [comment]
Hello Pat,

About two weeks ago I ran Thonny IDE for Python as sudo and the code
worked. But thanks for the instructions for I2C.

Have a great day,
Rastko
